services:
  - type: web
    name: Martes
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html
      - key: DB_HOST
        value: my-app-db
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: stock_db
      - key: DB_USER
        value: stock_user
      - key: DB_PASSWORD
        value: stock_password
    healthCheckPath: /AJAX/ListaOrdenarFiltrar/index.php
    autoDeploy: true

  - type: pserv
    name: my-app-db
    env: docker
    dockerfilePath: |
      FROM postgres:14-alpine
      COPY Martes/AJAX/ListaOrdenarFiltrar/init-postgres.sql /docker-entrypoint-initdb.d/
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: stock_db
      - key: POSTGRES_USER
        value: stock_user
      - key: POSTGRES_PASSWORD
        value: stock_password
