services:
  - type: pserv
    name: mysql-stock-db
    env: docker
    dockerfilePath: |
      FROM mysql:8.0
      COPY Martes/AJAX/ListaOrdenarFiltrar/init-mysql.sql /docker-entrypoint-initdb.d/
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root_password
      - key: MYSQL_DATABASE
        value: stock_db
      - key: MYSQL_USER
        value: stock_user
      - key: MYSQL_PASSWORD
        value: stock_password
    command: --default-authentication-plugin=mysql_native_password

  - type: web
    name: stock-management-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html
      - key: DB_HOST
        value: mysql-stock-db
      - key: DB_NAME
        value: stock_db
      - key: DB_USER
        value: stock_user
      - key: DB_PASSWORD
        value: stock_password
    healthCheckPath: /AJAX/ListaOrdenarFiltrar/index.php
    autoDeploy: true
