services:
  - type: web
    name: stock-management-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html
      # Apunta al nombre del servicio pserv de postgres
      - key: DB_HOST
        value: postgres-db
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: stock_db
      - key: DB_USER
        value: stock_user
      - key: DB_PASSWORD
        value: stock_password
    healthCheckPath: /AJAX/ListaOrdenarFiltrar/index.php
    autoDeploy: true

  - type: pserv
    name: postgres-db
    env: docker
    dockerfilePath: |
      FROM postgres:14-alpine
      # Copia el nuevo script de inicialización de Postgres
      COPY Martes/AJAX/ListaOrdenarFiltrar/init-postgres.sql /docker-entrypoint-initdb.d/
    plan: free
    envVars:
      # Variables de entorno para PostgreSQL
      - key: POSTGRES_DB
        value: stock_db
      - key: POSTGRES_USER
        value: stock_user
      - key: POSTGRES_PASSWORD
        value: stock_password
